import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import "../globals.css";
import QueryProvider from "../components/QueryProvider";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";

const vazirmatn = Vazirmatn({
  subsets: ["latin", "arabic"],
  display: "swap",
  variable: "--font-vazirmatn",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function LanguageSwitcher({ locale }: { locale: string }) {
  const otherLocale = locale === "en" ? "fa" : "en";
  return (
    <a
      href={`/${otherLocale}`}
      style={{ display: "flex", alignItems: "center", gap: 6 }}
      aria-label="Change language"
    >
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="20"
        height="20"
        fill="none"
        viewBox="0 0 24 24"
        style={{ display: "inline-block", verticalAlign: "middle" }}
      >
        <circle
          cx="12"
          cy="12"
          r="10"
          stroke="currentColor"
          strokeWidth="2"
          fill="none"
        />
        <path
          d="M2 12h20M12 2c2.5 3.5 2.5 16.5 0 20M12 2c-2.5 3.5-2.5 16.5 0 20"
          stroke="currentColor"
          strokeWidth="2"
          fill="none"
        />
      </svg>
      {otherLocale === "en" ? "English" : "فارسی"}
    </a>
  );
}

function Footer({ locale }: { locale: string }) {
  return (
    <footer
      style={{
        width: "100%",
        display: "flex",
        justifyContent: "flex-end",
        alignItems: "center",
        padding: "1rem 2rem",
        boxSizing: "border-box",
        position: "fixed",
        bottom: 0,
        right: 0,
        left: 0,
        background: "var(--background)",
        borderTop: "1px solid #eee",
        zIndex: 100,
      }}
    >
      <LanguageSwitcher locale={locale} />
    </footer>
  );
}

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = await getMessages();
  return (
    <html
      lang={locale}
      dir={locale === "fa" ? "rtl" : "ltr"}
      className={vazirmatn.variable}
    >
      <body
        style={{
          fontFamily:
            'Vazirmatn, "Segoe UI", "Tahoma", "Geneva", "Arial", "sans-serif"',
          minHeight: "100vh",
          paddingBottom: "60px", // space for footer
        }}
      >
        <NextIntlClientProvider messages={messages}>
          <QueryProvider>{children}</QueryProvider>
          <Footer locale={locale} />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
