import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import "../globals.css";
import QueryProvider from "@/contexts/QueryProvider";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider, useTranslations } from "next-intl";
import styles from "./layout.module.css";
import { CartIconButton } from "@/components/cart/CartIconButton";
import Link from "next/link";
import { LanguageSwitcher } from "@/components/footer/LanguageSwitcher";

const vazirmatn = Vazirmatn({
  subsets: ["latin", "arabic"],
  display: "swap",
  variable: "--font-vazirmatn",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Footer({ locale }: { locale: string }) {
  return (
    <footer className={styles.footer}>
      <div className={styles.footerContent}>
        <LanguageSwitcher locale={locale} />
      </div>
    </footer>
  );
}

function Header({ locale }: { locale: string }) {
  const t = useTranslations();
  const isRTL = locale === "fa";
  const headerClass = `${styles.header} ${
    isRTL ? styles.headerRtl : styles.headerLtr
  }`;
  const headerContentClass = `${styles.headerContent} ${
    isRTL ? styles.headerContentRtl : styles.headerContentLtr
  }`;
  const headerTextClass = `${styles.headerText} ${
    isRTL ? styles.headerTextRtl : styles.headerTextLtr
  }`;

  return (
    <header className={headerClass}>
      <div className={headerContentClass}>
        <div className={headerTextClass} style={{ flex: 1 }}>
          <Link href="/">
            <h1 className={styles.title}>
              {t("header")}
              <span className={styles.titleExclamation}>!</span>
            </h1>
          </Link>
          <p className={styles.subtitle}>{t("subheader")}</p>
        </div>
        <CartIconButton dir={isRTL ? "rtl" : "ltr"} />
      </div>
    </header>
  );
}

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = await getMessages();
  return (
    <html
      lang={locale}
      dir={locale === "fa" ? "rtl" : "ltr"}
      className={vazirmatn.variable}
    >
      <body className={styles.body}>
        <NextIntlClientProvider messages={messages}>
          <Header locale={locale} />
          <div className={`container ${styles.mainContainer}`}>
            <QueryProvider>{children}</QueryProvider>
          </div>
          <Footer locale={locale} />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
